# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in screen-count_object.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "capybara", "~> 3.40"
gem "selenium-webdriver", "~> 4.32"
gem "launchy", "~> 3"

gem "screen-base", "~> 0.1.0", path: "/home/tanya/Projects/screen-base/"
